### ISSUE TITLE
HRSC转COCO

### ISSUE THREAD

**Issue by ctgu123** [ming71/toolbox#11]
缺乏命名：
E:\Anaconda\python.exe "G:/CV projects/toolbox/converter/toCOCO/HRSC2COCO.py"
HRSC2COCOTrain:   0%|          | 0/436 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:/CV projects/toolbox/converter/toCOCO/HRSC2COCO.py", line 183, in <module>
    HRSC2COCOTrain(r'C:\Users\admin\Downloads\HRSC2016_dataset\HRSC2016\HRSC2016',
  File "G:/CV projects/toolbox/converter/toCOCO/HRSC2COCO.py", line 66, in HRSC2COCOTrain
    objects = parse_voc_poly(os.path.join(labelparent, filename+'.xml'))
  File "G:/CV projects/toolbox/converter/toCOCO/HRSC2COCO.py", line 159, in parse_voc_poly
    gtpoly = shgeo.Polygon(object_struct['poly'])
NameError: name 'shgeo' is not defined

Process finished with exit code 1

**Comment by Luian0297** [comment]
Have you solved this problem, please?

**Comment by shenhaibb** [comment]
import shapely.geometry as shgeo
